# Generated by Django 5.1.2 on 2025-02-25 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_recipecomment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecipeComment',
        ),
    ]
